/Compton/gun/mode 3
/Compton/gun/verbose 0
/Compton/run/runnumber 28
/Compton/run/autosave 1000
#/Compton/gun/ElectronEnergy 6.417 GeV
/Compton/gun/ElectronEnergy 1.95 GeV
#/Compton/gun/ElectronEnergy 3.4 GeV
#/Compton/gun/ElectronEnergy 10.617 GeV

/Compton/gun/LaserWavelenght 532 nm
#/Compton/gun/LaserWavelenght 1064 nm
#/Compton/gun/PhotonVertexZ 0.0 mm
/Compton/gun/PhotonVertexZ 0.0 mm
/Compton/gun/Initialize
/Compton/event/printevent 10
/Compton/step/OpticalMaxStepTime 250 ns
/Compton/detector/setoptions :ALL_IGNORE: store_edep_hits=no

/tracking/verbose 0
#/process/list
#/process/setVerbose 2 OpBoundary

/run/beamOn 1000
